blank_issues_enabled: false
contact_links:
  - name: Usage Questions (GitHub Discussions)
    url: https://github.com/dis_sqlalchemy/dis_sqlalchemy/discussions/new?category=Usage-Questions
    about: Questions and Answers for dis_sqlalchemy Users 
  - name: Live Chat on Gitter
    url: https://gitter.im/dis_sqlalchemy/community
    about: Searchable Web-Based Chat
  - name: dis_sqlalchemy Mailing List
    url: https://groups.google.com/forum/#!forum/dis_sqlalchemy
    about: Over a decade of questions and answers are here
  - name: Ideas / Feature Proposal (GitHub Discussions)
    url: https://github.com/dis_sqlalchemy/dis_sqlalchemy/discussions/new?category=Ideas
    about: Use this for initial discussion for new features and suggestions
  - name: dis_sqlalchemy Community Guide
    url: https://www.dis_sqlalchemy.org/support.html
    about: Start here for an overview of dis_sqlalchemy's support network and posting guidelines

